# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-02 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170428_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
