# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_proyecto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
