# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_trayecto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='clientes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
