# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_trayecto_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='partida',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
