# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Proyecto'),
        ),
    ]
