# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-23 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20170423_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='company',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url',
        ),
    ]
