# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_usuario_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='date_ride',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
