# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_trayecto_date_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='seats',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
