# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_trayecto_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='plates',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
