# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_trayecto_plates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='administrador',
        ),
        migrations.AddField(
            model_name='trayecto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Usuario'),
        ),
    ]
