# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20170424_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='latitudeDE',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='latitudeOR',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='longitudeDE',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='longitudeOR',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
